services:
  - type: web
    name: machine-server-1
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        generateValue: false
